//! Muna desktop shell (Tauri v2). Wires plugins, managed state and the typed IPC surface
//! generated by tauri-specta; everything platform-specific lives in `muna-platform` and
//! everything testable lives in `muna-core` (docs/03-architecture.md, ADR-0001).

// `unsafe` belongs to `muna-platform::windows` only (docs/03-architecture.md, crate boundaries).
#![forbid(unsafe_code)]

pub mod ipc;
pub mod paths;
pub mod shell;
pub mod state;

use std::sync::Arc;
use std::time::Instant;

use tauri::Manager;
use tauri_plugin_autostart::MacosLauncher;
use tauri_plugin_log::{Target, TargetKind};

pub use ipc::export_bindings;
use state::AppState;

/// Builds and runs the application. Never returns on success.
///
/// # Panics
///
/// Panics when Tauri fails to start, which is unrecoverable for a tray utility.
pub fn run() {
    let started_at = Instant::now();
    let specta = ipc::builder();

    // Keep the bindings on disk in sync while developing; CI enforces this with
    // `pnpm -w contracts:generate` + `git diff --exit-code` (docs/11-ci-cd.md).
    #[cfg(debug_assertions)]
    if let Err(error) = export_bindings(&ipc::default_bindings_path()) {
        eprintln!("failed to export tauri-specta bindings: {error}");
    }

    let profile_dir = paths::profile_dir();

    // Managed state must exist before the config windows are created: wry pumps messages
    // while it waits for each WebView2 controller, so a webview declared in tauri.conf.json
    // can invoke commands before `setup` runs (observed in docs/spikes/m0-window.md).
    let platform = muna_platform::default_platform();
    let mut state =
        AppState::open(&profile_dir, platform).expect("failed to open the Muna profile");
    if shell::spike::enabled() {
        state = state.with_spike(started_at, &profile_dir);
    }
    let state = Arc::new(state);

    tauri::Builder::default()
        // Must be the first plugin so a second launch is intercepted before anything else.
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            tracing::info!("second instance launched; focusing settings");
            if let Some(window) = app.get_webview_window("settings") {
                let _ = window.show();
                let _ = window.set_focus();
            }
        }))
        .plugin(
            tauri_plugin_log::Builder::new()
                .clear_targets()
                .targets([
                    Target::new(TargetKind::Stdout),
                    Target::new(TargetKind::Folder {
                        path: profile_dir.join("logs"),
                        file_name: Some("muna".into()),
                    }),
                ])
                .level(log::LevelFilter::Info)
                .max_file_size(5 * 1024 * 1024)
                .rotation_strategy(tauri_plugin_log::RotationStrategy::KeepSome(5))
                .build(),
        )
        .plugin(tauri_plugin_autostart::init(
            MacosLauncher::LaunchAgent,
            Some(vec!["--autostart"]),
        ))
        .plugin(tauri_plugin_global_shortcut::Builder::new().build())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .invoke_handler(specta.invoke_handler())
        .manage(Arc::clone(&state))
        .setup(move |app| {
            specta.mount_events(app);
            tracing::info!(platform = state.platform.name(), profile = %profile_dir.display(), "starting");

            if let Some(spike) = &state.spike {
                // The spike owns the notch windows; the settings window stays hidden so the
                // measurements see nothing but the notch.
                shell::spike::start(app.handle(), Arc::clone(spike));
                return Ok(());
            }

            // The notch window starts off-screen (placed by the shell once M1 lands) and there
            // is no tray icon yet (M1-E1), so the settings window is the only visible surface.
            if let Some(window) = app.get_webview_window("settings") {
                window.show()?;
            }
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("failed to start Muna");
}
