//! Muna desktop shell (Tauri v2). Wires plugins, managed state and the typed IPC surface
//! generated by tauri-specta; everything platform-specific lives in `muna-platform` and
//! everything testable lives in `muna-core` (docs/03-architecture.md, ADR-0001).

// `unsafe` belongs to `muna-platform::windows` only (docs/03-architecture.md, crate boundaries).
#![forbid(unsafe_code)]

pub mod activities;
pub mod ipc;
pub mod modules;
pub mod paths;
pub mod shell;
pub mod state;

use std::sync::Arc;
use std::time::Instant;

use tauri::{RunEvent, WindowEvent};
use tauri_plugin_log::{Target, TargetKind};

pub use ipc::export_bindings;
use state::AppState;

/// Argument appended to the launch-at-login command line so the settings window stays hidden
/// (`muna_platform::windows::AUTOSTART_ARG` mirrors it for the Windows implementation).
pub const AUTOSTART_ARG: &str = "--autostart";

/// Builds and runs the application. Never returns on success.
///
/// # Panics
///
/// Panics when Tauri fails to start, which is unrecoverable for a tray utility.
pub fn run() {
    let started_at = Instant::now();
    let specta = ipc::builder();

    // Keep the bindings on disk in sync while developing; CI enforces this with
    // `pnpm -w contracts:generate` + `git diff --exit-code` (docs/11-ci-cd.md).
    #[cfg(debug_assertions)]
    if let Err(error) = export_bindings(&ipc::default_bindings_path()) {
        eprintln!("failed to export tauri-specta bindings: {error}");
    }

    let profile_dir = paths::profile_dir();
    let autostarted = std::env::args().skip(1).any(|arg| arg == AUTOSTART_ARG);

    // Managed state must exist before the config windows are created: wry pumps messages
    // while it waits for each WebView2 controller, so a webview declared in tauri.conf.json
    // can invoke commands before `setup` runs (observed in docs/spikes/m0-window.md).
    let platform = muna_platform::default_platform();
    let mut state =
        AppState::open(&profile_dir, platform).expect("failed to open the Muna profile");
    if shell::spike::enabled() {
        state = state.with_spike(started_at, &profile_dir);
    } else {
        state = state.with_shell();
    }
    let state = Arc::new(state);
    let exit_state = Arc::clone(&state);

    tauri::Builder::default()
        // Must be the first plugin so a second launch is intercepted before anything else.
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            tracing::info!("second instance launched; focusing settings");
            shell::manager::ShellManager::open_settings(app);
        }))
        .plugin(
            tauri_plugin_log::Builder::new()
                .clear_targets()
                .targets([
                    Target::new(TargetKind::Stdout),
                    Target::new(TargetKind::Folder {
                        path: profile_dir.join("logs"),
                        file_name: Some("muna".into()),
                    }),
                ])
                .level(log::LevelFilter::Info)
                .max_file_size(5 * 1024 * 1024)
                .rotation_strategy(tauri_plugin_log::RotationStrategy::KeepSome(5))
                .build(),
        )
        .plugin(tauri_plugin_global_shortcut::Builder::new().build())
        .plugin(tauri_plugin_updater::Builder::new().build())
        // Native file dialogs and Explorer for settings import/export and the logs folder;
        // both are driven from Rust commands, so no JS permissions are granted.
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(specta.invoke_handler())
        .manage(Arc::clone(&state))
        .setup(move |app| {
            specta.mount_events(app);
            tracing::info!(
                platform = state.platform.name(),
                profile = %profile_dir.display(),
                autostarted,
                "starting"
            );

            if let Some(spike) = &state.spike {
                // The spike owns the notch windows; the settings window stays hidden so the
                // measurements see nothing but the notch.
                shell::spike::start(app.handle(), Arc::clone(spike));
                return Ok(());
            }

            if let Some(shell) = &state.shell {
                shell.start(app.handle());
            }
            // Strip content flows hub → event; the module backends publish into the hub, and
            // the media module additionally reports its state through typed events.
            activities::start(app.handle(), &state.activities);
            state
                .modules
                .media
                .set_sink(Arc::new(ipc::MediaEventSink::new(app.handle().clone())));
            let started = modules::start_all(&state.module_ctx(), &state.modules);
            tracing::info!(modules = ?started, "modules running");
            let settings = state.settings.lock().clone();
            state.apply_module_settings(&settings);
            state.sync_autostart(app.handle(), settings.general.launch_at_login);

            // The tray icon is the everyday entry point; the settings window only opens by
            // itself on the very first launch (docs/modules/notch-shell.md).
            if state.first_run && !autostarted {
                shell::manager::ShellManager::open_settings(app.handle());
            }
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("failed to start Muna")
        .run(move |_app, event| match event {
            RunEvent::Exit => {
                if let Some(shell) = &exit_state.shell {
                    shell.shutdown();
                }
            }
            RunEvent::WindowEvent {
                label,
                event: WindowEvent::Destroyed,
                ..
            } => {
                // A destroyed notch window must not keep the strip suspended.
                exit_state.activities.forget_window(&label);
            }
            _ => {}
        });
}
