// @ts-check
import path from 'node:path';

import js from '@eslint/js';
import prettier from 'eslint-config-prettier/flat';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactHooks from 'eslint-plugin-react-hooks';
import storybook from 'eslint-plugin-storybook';
import tailwind from 'eslint-plugin-tailwindcss';
import { defineConfig, globalIgnores } from 'eslint/config';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default defineConfig(
  globalIgnores([
    '**/node_modules/',
    '**/dist/',
    '**/target/',
    '**/coverage/',
    '**/storybook-static/',
    '**/playwright-report/',
    '**/test-results/',
    // Generated by tauri-specta; regenerated and diffed in CI, never hand-edited.
    'packages/contracts/src/bindings.ts',
  ]),

  // Plain JavaScript (Node scripts, config files): recommended rules, no type information.
  {
    files: ['**/*.{js,mjs,cjs}'],
    extends: [js.configs.recommended],
    languageOptions: { globals: globals.node },
  },

  // TypeScript with type information (strict + stylistic), React hooks and accessibility.
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.strictTypeChecked,
      tseslint.configs.stylisticTypeChecked,
      reactHooks.configs.flat.recommended,
      jsxA11y.flatConfigs.recommended,
      tailwind.configs.recommended,
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: { ...globals.browser, ...globals.node },
    },
    settings: {
      tailwindcss: {
        // Tailwind v4 has no JS config: point the plugin at the CSS entry that imports it.
        // Absolute, because the plugin resolves relative paths from each package root.
        cssConfigPath: path.join(import.meta.dirname, 'apps/desktop/src/styles.css'),
      },
    },
    rules: {
      // Explicit prop types on components; module entry points may default-export.
      'no-restricted-syntax': [
        'error',
        {
          selector: 'ExportDefaultDeclaration',
          message:
            'Use named exports. Default exports are only allowed in module entry points (index.ts), config files and Storybook stories.',
        },
      ],
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
      'react-hooks/exhaustive-deps': 'error',
      // Tailwind v4 utilities are resolved from CSS; the plugin's class registry is incomplete.
      'tailwindcss/no-custom-classname': 'off',
    },
  },

  // Files that legitimately default-export: config, stories, module entry points, entry HTML scripts.
  {
    files: [
      '**/*.config.{ts,mts}',
      '**/.storybook/**/*.{ts,tsx}',
      '**/*.stories.{ts,tsx}',
      '**/modules/*/index.ts',
      '**/vite-env.d.ts',
    ],
    rules: { 'no-restricted-syntax': 'off' },
  },

  // Storybook stories.
  {
    files: ['**/*.stories.{ts,tsx}'],
    extends: [storybook.configs['flat/recommended']],
  },

  // Tests: relax rules that fight assertion helpers.
  {
    files: ['**/*.test.{ts,tsx}', '**/vitest.setup.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
    },
  },

  // Prettier owns formatting; must stay last.
  prettier,
);
