/* eslint-disable */
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	/**  Persists the whole settings document and broadcasts `SettingsChanged`. */
	updateSettings: (settings: Settings) => typedError<Settings, IpcError>(__TAURI_INVOKE("update_settings", { settings })),
	getStripContent: () => __TAURI_INVOKE<StripContent>("get_strip_content"),
	getShellMode: () => __TAURI_INVOKE<ShellMode>("get_shell_mode"),
	/**  The UI has painted its first frame; the shell may move the window into place. */
	shellReady: () => typedError<null, IpcError>(__TAURI_INVOKE("shell_ready")),
	/**
	 *  Publishes the painted shapes so pointer events outside them pass through. The first rect
	 *  is the strip (the yield rules measure caption overlap against it).
	 */
	publishShapeRects: (rects: ShapeRect[]) => typedError<null, IpcError>(__TAURI_INVOKE("publish_shape_rects", { rects })),
	/**  Records the frame statistics of one morph (spike log; debug trace in the product shell). */
	reportMorph: (report: MorphReport) => __TAURI_INVOKE<void>("report_morph", { report }),
	/**
	 *  Layout of the calling notch window; `None` until the shell has attached it (the UI then
	 *  waits for `ShellLayoutChanged`).
	 */
	getShellLayout: () => typedError<{
	label: string,
	monitorId: string,
	isPrimary: boolean,
	enabled: boolean,
	mode: PlacementMode,
	shape: NotchShape,
	/**  Strip height preset in CSS px (32 / 26 / 38). */
	stripHeight: number,
	/**  CSS px between the window's top edge and the strip (0 for Notch, 8 for Island). */
	stripTopOffset: number,
	/**  `min(1000, monitorWidth − 80)`. */
	panelMaxWidth: number,
	/**  Monitor scale as a whole percentage (100, 125, 150, …). */
	scalePercent: number,
	yieldState: YieldState,
} | null, IpcError>(__TAURI_INVOKE("get_shell_layout")),
	/**
	 *  The calling notch window wants (or no longer wants) to take keyboard focus (a text field
	 *  gained focus while Pinned). Toggles `WS_EX_NOACTIVATE`.
	 */
	setNotchFocusable: (focusable: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("set_notch_focusable", { focusable })),
	/**  Parks the notch on one display until resumed (tray: "Pause on display"). */
	setDisplayPaused: (monitorId: string, paused: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("set_display_paused", { monitorId, paused })),
	/**  Shows and focuses the settings window. */
	openSettings: () => __TAURI_INVOKE<void>("open_settings"),
	/**  Quits the app, releasing OS reservations first. */
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
};

/** Events */
export const events = {
	morphRequested: makeEvent<MorphRequested>("morph-requested"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
	shellLayoutChanged: makeEvent<ShellLayoutChanged>("shell-layout-changed"),
	shellToggleRequested: makeEvent<ShellToggleRequested>("shell-toggle-requested"),
	shellYieldChanged: makeEvent<ShellYieldChanged>("shell-yield-changed"),
	stripContentChanged: makeEvent<StripContentChanged>("strip-content-changed"),
};

/* Types */
/**  Long-lived strip content owned by a module. */
export type Activity = {
	id: string,
	module: string,
	/**  0–100; higher wins. Module defaults live in docs/modules/*.md. */
	priority: number,
	/**  Leading slot descriptor (`"image"`, `"icon:battery"`, …); the UI maps it to a view. */
	leading: string | null,
	trailing: string | null,
	/**  Optional text for the wide (expanded strip) layout. */
	wideText: string | null,
};

/**  Static facts about the running build, for the settings "About" section and diagnostics. */
export type AppInfo = {
	name: string,
	version: string,
	/**  `"windows"` or `"fake"`. */
	platform: string,
	profileDir: string,
};

export type GeneralSettings = {
	launchAtLogin: boolean,
	reducedMotion: ReducedMotion,
	/**  Accent name from docs/05-design-system.md (`blue`, `purple`, …). */
	accent: string,
};

/**  Error shape every command returns. Messages are safe to show and to log (no user data). */
export type IpcError = {
	/**  Stable machine-readable code (`settings.io`, `store.sqlite`, `platform.unsupported`). */
	code: string,
	message: string,
};

/**
 *  Export-only mirror of `serde_json::Value` for the generated TypeScript (`JsonValue`).
 * 
 *  specta-typescript refuses `serde_json`'s 64-bit integer variants, so [`Settings::modules`]
 *  declares this shape for TypeScript while the runtime keeps `serde_json::Value`.
 */
export type JsonValue = null | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

/**  Everything the shell needs for one monitor. */
export type MonitorLayout = {
	/**
	 *  `false` removes the notch from this monitor: its window is parked off-screen and the
	 *  UI pauses, so re-enabling is instant.
	 */
	enabled: boolean,
	mode: PlacementMode,
	shape: NotchShape,
	/**  Horizontal offset from the monitor centre, CSS px (positive = right). */
	offsetX: number,
	/**  Vertical offset from the top edge, CSS px. Island adds its own 6–8 px on top. */
	offsetY: number,
	stripHeight: StripHeight,
};

/**
 *  Frame statistics the UI measured during one strip ↔ panel morph. Integers only: specta
 *  exports floats as `number | null`.
 */
export type MorphReport = {
	expanded: boolean,
	frames: number,
	durationUs: number,
	maxFrameUs: number,
	/**  Frames whose delta exceeded 1.5 × 16.7 ms. */
	droppedFrames: number,
};

/**  Asks every notch window to morph (spike shortcut `Ctrl+Alt+M` or scripted run). */
export type MorphRequested = {
	expanded: boolean,
};

/**
 *  Notch (flush with the top edge, flared) or Island (floating capsule); see
 *  docs/05-design-system.md "Shape".
 */
export type NotchShape = "notch" | "island";

/**  Short, self-dismissing strip content. */
export type Notice = {
	id: string,
	module: string,
	priority: number,
	text: string,
	/**  How long the notice holds the strip. */
	holdMs: number,
};

/**
 *  Overlay draws over other windows and yields; Reserved registers an `AppBar` of strip height
 *  so maximised windows start below the strip (ADR-0002 consequences).
 */
export type PlacementMode = "overlay" | "reserved";

export type ReducedMotion = 
/**  Follow the Windows "animation effects" setting (default). */
"system" | "on" | "off";

export type Settings = {
	version: number,
	general: GeneralSettings,
	/**  Notch placement per monitor and the global shell switches (v2). */
	shell: ShellSettings,
	/**  Per-module settings keyed by module id; each module validates its own namespace. */
	modules: { [key in string]: JsonValue },
};

export type SettingsChanged = {
	settings: Settings,
};

/**
 *  A painted shape in whole CSS pixels relative to the window's client area (the UI rounds
 *  `DOMRect`s). Rust converts it to physical screen pixels for hit-testing
 *  (docs/modules/notch-shell.md).
 */
export type ShapeRect = {
	x: number,
	y: number,
	width: number,
	height: number,
};

/**
 *  What the UI needs to render one notch window (`ShellLayoutChanged`, `get_shell_layout`).
 *  CSS px throughout; the window itself is always [`layout::WINDOW_LOGICAL`].
 */
export type ShellLayout = {
	label: string,
	monitorId: string,
	isPrimary: boolean,
	enabled: boolean,
	mode: PlacementMode,
	shape: NotchShape,
	/**  Strip height preset in CSS px (32 / 26 / 38). */
	stripHeight: number,
	/**  CSS px between the window's top edge and the strip (0 for Notch, 8 for Island). */
	stripTopOffset: number,
	/**  `min(1000, monitorWidth − 80)`. */
	panelMaxWidth: number,
	/**  Monitor scale as a whole percentage (100, 125, 150, …). */
	scalePercent: number,
	yieldState: YieldState,
};

/**
 *  A notch window's layout changed (attached, monitor or settings changed). Emitted to every
 *  window; the payload names the window it is about.
 */
export type ShellLayoutChanged = {
	layout: ShellLayout,
};

/**  Which UI the notch window should render. */
export type ShellMode = 
/**  The product shell. */
"normal" | 
/**  The M0-E2 window spike (`MUNA_SPIKE=window`, docs/spikes/m0-window.md). */
"spikeWindow";

/**  Global shell settings plus the per-monitor table. */
export type ShellSettings = {
	/**  `WDA_EXCLUDEFROMCAPTURE` on every notch window. */
	hideFromCaptures: boolean,
	/**
	 *  Global shortcut that expands or collapses the notch under the cursor
	 *  (`tauri-plugin-global-shortcut` syntax).
	 */
	toggleHotkey: string,
	/**  Layout used for monitors without an entry in `monitors`. */
	defaults: MonitorLayout,
	/**  Per-monitor overrides keyed by the stable monitor id (`\\.\DISPLAY1`, …). */
	monitors: { [key in string]: MonitorLayout },
};

/**  The global toggle hotkey was pressed; `label` is the notch on the monitor under the cursor. */
export type ShellToggleRequested = {
	label: string,
};

/**  The yield rules changed their mind about one notch window (docs/modules/notch-shell.md). */
export type ShellYieldChanged = {
	label: string,
	state: YieldState,
};

/**  What the closed strip renders right now. */
export type StripContent = { kind: "idle" } | { kind: "activity"; activity: Activity } | { kind: "notice"; notice: Notice };

export type StripContentChanged = {
	content: StripContent,
};

/**  Strip height presets: 32 (Default) · 26 (Compact) · 38 (Comfortable) CSS px. */
export type StripHeight = "compact" | "default" | "comfortable";

/**  What one notch window does about the world around it. */
export type YieldState = 
/**  Nothing in the way. */
"none" | 
/**  A title bar or a window drag is under the strip: the UI slides the strip up to 6 px. */
"peek" | 
/**  Fullscreen, locked or paused: the window is moved above the monitor and the UI pauses. */
"parked";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

