/* eslint-disable */
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	/**  Persists the whole settings document and broadcasts `SettingsChanged`. */
	updateSettings: (settings: Settings) => typedError<Settings, IpcError>(__TAURI_INVOKE("update_settings", { settings })),
	getStripContent: () => __TAURI_INVOKE<StripContent>("get_strip_content"),
	getShellMode: () => __TAURI_INVOKE<ShellMode>("get_shell_mode"),
	/**  The UI has painted its first frame; the shell may move the window into place. */
	shellReady: () => typedError<null, IpcError>(__TAURI_INVOKE("shell_ready")),
	/**  Publishes the painted shapes so pointer events outside them pass through. */
	publishShapeRects: (rects: ShapeRect[]) => typedError<null, IpcError>(__TAURI_INVOKE("publish_shape_rects", { rects })),
	/**  Records the frame statistics of one morph. */
	reportMorph: (report: MorphReport) => typedError<null, IpcError>(__TAURI_INVOKE("report_morph", { report })),
};

/** Events */
export const events = {
	morphRequested: makeEvent<MorphRequested>("morph-requested"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
	stripContentChanged: makeEvent<StripContentChanged>("strip-content-changed"),
};

/* Types */
/**  Long-lived strip content owned by a module. */
export type Activity = {
	id: string,
	module: string,
	/**  0–100; higher wins. Module defaults live in docs/modules/*.md. */
	priority: number,
	/**  Leading slot descriptor (`"image"`, `"icon:battery"`, …); the UI maps it to a view. */
	leading: string | null,
	trailing: string | null,
	/**  Optional text for the wide (expanded strip) layout. */
	wideText: string | null,
};

/**  Static facts about the running build, for the settings "About" section and diagnostics. */
export type AppInfo = {
	name: string,
	version: string,
	/**  `"windows"` or `"fake"`. */
	platform: string,
	profileDir: string,
};

export type GeneralSettings = {
	launchAtLogin: boolean,
	reducedMotion: ReducedMotion,
	/**  Accent name from docs/05-design-system.md (`blue`, `purple`, …). */
	accent: string,
};

/**  Error shape every command returns. Messages are safe to show and to log (no user data). */
export type IpcError = {
	/**  Stable machine-readable code (`settings.io`, `store.sqlite`, `platform.unsupported`). */
	code: string,
	message: string,
};

/**
 *  Export-only mirror of `serde_json::Value` for the generated TypeScript (`JsonValue`).
 * 
 *  specta-typescript refuses `serde_json`'s 64-bit integer variants, so [`Settings::modules`]
 *  declares this shape for TypeScript while the runtime keeps `serde_json::Value`.
 */
export type JsonValue = null | boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

/**
 *  Frame statistics the UI measured during one strip ↔ panel morph. Integers only: specta
 *  exports floats as `number | null`.
 */
export type MorphReport = {
	expanded: boolean,
	frames: number,
	durationUs: number,
	maxFrameUs: number,
	/**  Frames whose delta exceeded 1.5 × 16.7 ms. */
	droppedFrames: number,
};

/**  Asks every notch window to morph (spike shortcut `Ctrl+Alt+M` or scripted run). */
export type MorphRequested = {
	expanded: boolean,
};

/**  Short, self-dismissing strip content. */
export type Notice = {
	id: string,
	module: string,
	priority: number,
	text: string,
	/**  How long the notice holds the strip. */
	holdMs: number,
};

export type ReducedMotion = 
/**  Follow the Windows "animation effects" setting (default). */
"system" | "on" | "off";

export type Settings = {
	version: number,
	general: GeneralSettings,
	/**  Per-module settings keyed by module id; each module validates its own namespace. */
	modules: { [key in string]: JsonValue },
};

export type SettingsChanged = {
	settings: Settings,
};

/**
 *  A painted shape in whole CSS pixels relative to the window's client area (the UI rounds
 *  `DOMRect`s). Rust converts it to physical screen pixels for hit-testing
 *  (docs/modules/notch-shell.md).
 */
export type ShapeRect = {
	x: number,
	y: number,
	width: number,
	height: number,
};

/**  Which UI the notch window should render. */
export type ShellMode = 
/**  The product shell. */
"normal" | 
/**  The M0-E2 window spike (`MUNA_SPIKE=window`, docs/spikes/m0-window.md). */
"spikeWindow";

/**  What the closed strip renders right now. */
export type StripContent = { kind: "idle" } | { kind: "activity"; activity: Activity } | { kind: "notice"; notice: Notice };

export type StripContentChanged = {
	content: StripContent,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

