/**
 * Public surface of the IPC contract. `commands` and `events` are generated by tauri-specta
 * (`pnpm -w contracts:generate`); never hand-write `invoke('…')` strings in the UI.
 */
export { commands, events } from './bindings';
export type {
  Activity,
  AppInfo,
  GeneralSettings,
  IpcError,
  JsonValue,
  Notice,
  ReducedMotion,
  Settings,
  SettingsChanged,
  StripContent,
  StripContentChanged,
} from './bindings';
export * from './result';
export * from './schemas';
